name: Java app image Windows

on:
  schedule:
    - cron: '0 10 10 * *'
  workflow_call:
    inputs:
      semVerNum:
        type: string
        description: 'The Major.Minor.Patch part of the version'
        required: true
      revisionNum:
        type: string
        description: 'The revision number'
        required: true
      semVerSuffix:
        type: string
        description: 'The suffix of the version, including dash'
        required: true
      sign:
        type: boolean
        description: 'Sign binaries'
        default: true
      upload-to-draft:
        type: boolean
        default: true
    outputs:
      sha256-win-zip-x64:
        description: "SHA256 sum of the x64 zip"
        value: ${{ jobs.build-binary.outputs.sha256sum}}
  workflow_dispatch:
    inputs:
      semVerNum:
        description: 'The Major.Minor.Patch part of the version'
        required: false
      revisionNum:
        description: 'The revision number'
        required: false
      semVerSuffix:
        description: 'The suffix of the version, including dash'
        required: false
        default: '-SNAPSHOT'
      sign:
        description: 'Sign binaries'
        required: false
        type: boolean

permissions:
  contents: write

env:
  JAVA_DIST: 'temurin'
  JAVA_VERSION: '25.0.4+7'
  VERSION_NUM: ${{ inputs.semVerNum || '99.99.99' }}
  VERSION_SUFFIX: ${{ inputs.semVerSuffix || '' }}

defaults:
  run:
    shell: bash

jobs:
  build-binary:
    name: Build java app image
    runs-on: windows-latest
    outputs:
      sha256sum: ${{ steps.sha256sum.outputs.value }}
    env:
        ARTIFACT_NAME: cryptomator-cli-${{ inputs.semVerNum || '99.99.99' }}${{ inputs.semVerSuffix || '' }}-win-x64.zip
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 #v4.8.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${VERSION_NUM}${VERSION_SUFFIX}"
      - name: Run maven
        run: ./mvnw -B clean package -DskipTests
      - name: Patch target dir
        run: |
          cp LICENSE.txt target
          cp target/cryptomator-*.jar target/mods
      - name: Run jlink
        run: |
          envsubst < dist/jlink.args > target/jlink.args
          "${JAVA_HOME}/bin/jlink" '@./target/jlink.args'
      - name: Run jpackage
        run: |
          envsubst < dist/jpackage.args > target/jpackage.args
          "${JAVA_HOME}/bin/jpackage" '@./target/jpackage.args' --win-console
        env:
          JP_APP_VERSION: ${{ env.VERSION_NUM }}
          APP_VERSION: ${{ env.VERSION_NUM }}${{ env.VERSION_SUFFIX }}
          NATIVE_ACCESS_PACKAGE: org.cryptomator.jfuse.win
      - name: Update app dir
        run: |
          cp LICENSE.txt target/cryptomator-cli
          cp target/cryptomator-cli_completion.sh target/cryptomator-cli
      - name: Fix permissions
        run: attrib -r target/cryptomator-cli/cryptomator-cli.exe
        shell: pwsh
      - name: Extract jars with DLLs for Codesigning
        if: inputs.sign || github.event_name == 'schedule'
        shell: pwsh
        run: |
          Add-Type -AssemblyName "System.io.compression.filesystem"
          $jarFolder = Resolve-Path ".\target\Cryptomator-cli\app\mods"
          $jarExtractDir = New-Item -Path ".\target\jar-extract" -ItemType Directory

          #for all jars inspect
          Get-ChildItem -Path $jarFolder -Filter "*.jar" | ForEach-Object {
              $jar = [Io.compression.zipfile]::OpenRead($_.FullName)
              if (@($jar.Entries | Where-Object {$_.Name.ToString().EndsWith(".dll")} | Select-Object -First 1).Count -gt 0) {
                  #jars containing dlls extract
                  Set-Location $jarExtractDir
                  Expand-Archive -Path $_.FullName
              }
              $jar.Dispose()
          }
      - name: Codesign with Azure Trusted Signing
        if: inputs.sign || github.event_name == 'schedule'
        uses: azure/artifact-signing-action@c7ab2a863ab5f9a846ddb8265964877ef296ee82 # v2.0.0
        with:
          files-folder: ${{ github.workspace }}\target
          files-folder-filter: 'exe,dll'
          files-folder-recurse: true
          append-signature: true
          description: 'Cryptomator CLI'
          description-url: 'https://cryptomator.org'
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          signing-account-name: cryptomatorSigning
          certificate-profile-name: production
          endpoint: https://weu.codesigning.azure.net/
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          exclude-environment-credential: false
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: true
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true
      - name: Replace DLLs inside jars with signed ones
        if: inputs.sign || github.event_name == 'schedule'
        shell: pwsh
        run: |
          $jarExtractDir = Resolve-Path ".\target\jar-extract"
          $jarFolder = Resolve-Path ".\target\cryptomator-cli\app\mods"
          Get-ChildItem -Path $jarExtractDir | ForEach-Object {
              $jarName = $_.Name
              $jarFile = "${jarFolder}\${jarName}.jar"
              Set-Location $_
              Get-ChildItem -Path $_ -Recurse -File "*.dll" | ForEach-Object {
                  # update jar with signed dll
                  jar --file="$jarFile" --update $(Resolve-Path -Relative -Path $_)
              }
          }
      - name: Zip binary for release
        shell: pwsh
        run: Compress-Archive -Path .\target\cryptomator-cli -DestinationPath ".\${env:ARTIFACT_NAME}"
      - name: Compute SHA256 sum
        id: sha256sum
        run: |
          read -ra CMD_OUTPUT < <(sha256sum "./${ARTIFACT_NAME}")
          echo "value=${CMD_OUTPUT[0]}" >> "$GITHUB_OUTPUT"
      - name: Create detached GPG signature with key 615D449FE6E6A235
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --quiet --import
          echo "${GPG_PASSPHRASE}" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 615D449FE6E6A235 --detach-sign -a "./${ARTIFACT_NAME}"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cryptomator-cli-win-x64
          path: |
            ${{ env.ARTIFACT_NAME}}
            *.asc
          if-no-files-found: error
      - name: Publish zip on GitHub Releases
        if: inputs.upload-to-draft
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          draft: true
          fail_on_unmatched_files: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          files: |
            ${{ env.ARTIFACT_NAME}}
            cryptomator-*.asc
