name: Draft a Cryptomator CLI Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: '24.0.0+36'

defaults:
  run:
    shell: bash

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version: ''

  create-release-draft:
    name: Compile and Test
    runs-on: ubuntu-latest
    needs: get-version
    if: needs.get-version.outputs.versionType != 'unknown'
    outputs:
      TAR_SHA256: ${{ steps.tar-sha256.outputs.value }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
        with:
          fetch-depth: 0
      - name: Check the git tag is signed
        run: git cat-file -p "${GITHUB_REF_NAME}" | grep "BEGIN SSH SIGNATURE"
      - name: Check the git tag is on release or main branch
        run: git branch -r --contains "${GITHUB_REF_NAME}" | grep -E '^\s*origin/(main|release/.*)\s*$'
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 #v4.8.0
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and Test
        run: ./mvnw -B verify
      - name: Draft a release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          draft: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          generate_release_notes: true
          body_path: .github/release-body.md.template
      - name: Download source tarball
        run: |
          curl --silent --fail-with-body --proto "=https" -L -H "Accept: application/vnd.github+json" https://github.com/cryptomator/cli/archive/${GITHUB_REF_NAME}.tar.gz --output cryptomator-cli-${GITHUB_REF_NAME}.tar.gz
      - name: Compute SHA256 sum of tarball
        id: tar-sha256
        run: |
          read -ra CMD_OUTPUT < <(sha256sum "cryptomator-cli-${GITHUB_REF_NAME}.tar.gz")
          echo "value=${CMD_OUTPUT[0]}" >> $GITHUB_OUTPUT
      - name: Sign source tarball with key 615D449FE6E6A235
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --quiet --import
          echo "${GPG_PASSPHRASE}" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 615D449FE6E6A235 --detach-sign -a cryptomator-cli-*.tar.gz
        env:
          GPG_PRIVATE_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
      - name: Publish asc on GitHub Releases
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          draft: true
          fail_on_unmatched_files: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          files: |
            cryptomator-cli-*.tar.gz.asc

  build-linux:
    needs: [get-version, create-release-draft]
    uses: ./.github/workflows/build-linux.yml
    with:
      semVerNum: ${{needs.get-version.outputs.semVerNum}}
      revisionNum: ${{needs.get-version.outputs.revNum}}
      semVerSuffix: ${{needs.get-version.outputs.semVerSuffix}}
    secrets: inherit

  build-mac:
    needs: [get-version, create-release-draft]
    uses: ./.github/workflows/build-mac.yml
    with:
      semVerNum: ${{needs.get-version.outputs.semVerNum}}
      revisionNum: ${{needs.get-version.outputs.revNum}}
      semVerSuffix: ${{needs.get-version.outputs.semVerSuffix}}
    secrets: inherit

  build-win:
    needs: [get-version, create-release-draft]
    uses: ./.github/workflows/build-win.yml
    with:
      semVerNum: ${{needs.get-version.outputs.semVerNum}}
      revisionNum: ${{needs.get-version.outputs.revNum}}
      semVerSuffix: ${{needs.get-version.outputs.semVerSuffix}}
    secrets: inherit

  update-sha256sums:
    runs-on: ubuntu-latest
    needs: [get-version, create-release-draft, build-linux, build-mac, build-win]
    env:
      SEMVER: ${{ needs.get-version.outputs.semVerStr }}
      GH_TOKEN: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - name: Update release body with checksums
        run: |
          CURRENT_BODY=$(gh release view "${GITHUB_REF_NAME}" --json body --jq .body)
          RELEASE_BODY=$(printf '%s\n' "${CURRENT_BODY}" | sed '/<!-- HEADER -->/,/<!-- \/HEADER -->/c\
          <!-- HEADER -->\
          > [!NOTE]\
          > Release artifacts finished building successfully.\
          >\
          > SHA-256 checksums have been updated below.\
          <!-- /HEADER -->')

          export TARBALL="${SRC_SHA}  cryptomator-cli-${SEMVER}.tar.gz"
          export WIN_x64="${WIN_SHA}  cryptomator-cli-${SEMVER}-win-x64.zip"
          export MAC_arm64="${MAC_ARM64_SHA}  cryptomator-cli-${SEMVER}-mac-arm64.zip"
          export MAC_x64="${MAC_X64_SHA}  cryptomator-cli-${SEMVER}-mac-x64.zip"
          export LINUX_x64="${LINUX_X64_SHA}  cryptomator-cli-${SEMVER}-linux-x64.zip"
          export LINUX_aarch64="${LINUX_AARCH64_SHA}  cryptomator-cli-${SEMVER}-linux-aarch64.zip"

          envsubst '$VERSION $TARBALL $WIN_x64 $MAC_arm64 $MAC_x64 $LINUX_x64 $LINUX_aarch64' \
            <<< "${RELEASE_BODY}" \
            > release-body.md

          gh release edit "${GITHUB_REF_NAME}" --draft --notes-file release-body.md
        env:
          VERSION: ${{ needs.get-version.outputs.semVerStr }}
          SRC_SHA: ${{ needs.create-release-draft.outputs.TAR_SHA256 }}
          WIN_SHA: ${{ needs.build-win.outputs.sha256-win-zip-x64 }}
          MAC_ARM64_SHA: ${{ needs.build-mac.outputs.sha256-mac-zip-arm64 }}
          MAC_X64_SHA: ${{ needs.build-mac.outputs.sha256-mac-zip-x64 }}
          LINUX_X64_SHA: ${{ needs.build-linux.outputs.sha256-linux-zip-x64 }}
          LINUX_AARCH64_SHA: ${{ needs.build-linux.outputs.sha256-linux-zip-aarch64 }}
